var firstname="saranya";
var lastname="panday";
var wholename=firstname.concat(lastname);
console.log(wholename);
var age=wholename.replace("panday"," age is 10");
console.log(age);
var captitalname=wholename.toUpperCase();
console.log(captitalname);
var x=Math.sqrt(49);
console.log(x);
var y=Math.max(24,67,2,57,12,31,40);
console.log(y);
var powernumber=Math.pow(10,5);
console.log(powernumber);
var decimal=23.45678902346;
var num_fixed=decimal.toFixed(3);
console.log(num_fixed);
var addition= 7+25+67+90;
console.log(addition);
var subtract= 78-31;
console.log(subtract);
console.log(typeof powernumber);
console.log(typeof wholename);
